"""empty message

Revision ID: 2e7679aa003d
Revises: 20f55566fae5
Create Date: 2023-01-24 23:34:44.157036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e7679aa003d'
down_revision = '20f55566fae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
