"""empty message

Revision ID: 323eb977a623
Revises: e2375563c9fb
Create Date: 2023-01-25 00:31:17.513882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '323eb977a623'
down_revision = 'e2375563c9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('ascii',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('feat_class',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('feat_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('cc2',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('admin1',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('admin2',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('admin3',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('admin4',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('population',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('elevation',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('dem',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('tz',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('modified_at',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('modified_at',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('tz',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('dem',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('elevation',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin4',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin3',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin2',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin1',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('cc2',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('feat_code',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('feat_class',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('ascii',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
